version: '2'
services:
    jhipsterapplicationangularjs-app:
        image: jhipsterapplicationangularjs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapplicationangularjs-mysql:3306/jhipsterapplicationangularjs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsterapplicationangularjs-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterapplicationangularjs-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapplicationangularjs-mysql
    jhipsterapplicationangularjs-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterapplicationangularjs-elasticsearch
